<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HPDA0126" name="com.qait.demo.tests.TestLevel2_added_test_cases" tests="10" failures="0" timestamp="4 Nov 2016 13:43:28 GMT" time="136.005" errors="2">
  <testcase name="TestStep10_Checkout" time="60.085" classname="com.qait.demo.tests.TestLevel2_added_test_cases">
    <error type="java.lang.AssertionError" message="FAILED: Element verify_procced_to_chkout not found on the HomePage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element verify_procced_to_chkout not found on the HomePage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:84)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:62)
	at com.qait.demo.keywords.ProductDetailsActions.clickProceedToChkout(ProductDetailsActions.java:62)
	at com.qait.demo.tests.TestLevel2_added_test_cases.TestStep10_Checkout(TestLevel2_added_test_cases.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- TestStep10_Checkout -->
  <testcase name="TestStep4_SelectTablets" time="2.249" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
  <testcase name="TestStep9_AddProductToCart" time="63.033" classname="com.qait.demo.tests.TestLevel2_added_test_cases">
    <error type="java.lang.AssertionError" message="FAILED: Element verify_view_cart not found on the HomePage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element verify_view_cart not found on the HomePage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:84)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:62)
	at com.qait.demo.keywords.ProductDetailsActions.verifyViewCartBtn(ProductDetailsActions.java:43)
	at com.qait.demo.tests.TestLevel2_added_test_cases.TestStep9_AddProductToCart(TestLevel2_added_test_cases.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- TestStep9_AddProductToCart -->
  <testcase name="TestStep8_verifyProductPage" time="5.297" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
  <testcase name="TestStep1_VerifyCartImage" time="0.083" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
  <testcase name="TestStep3_SearchProduct" time="2.204" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
  <testcase name="TestStep7_SelectFirstProduct" time="0.267" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
  <testcase name="TestStep5_VerifySortTab" time="0.569" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
  <testcase name="TestStep2_VerifySignIn" time="0.062" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
  <testcase name="TestStep6_SelectBrand" time="2.156" classname="com.qait.demo.tests.TestLevel2_added_test_cases"/>
</testsuite> <!-- com.qait.demo.tests.TestLevel2_added_test_cases -->
